export const portfolio = {
  person: {
    name: "Aarav Shah",
    location: "Frisco, Texas",
    email: "aaraven99@gmail.com",
    linkedIn: "https://linkedin.com/in/aarav-shah-eng",
    school: "Panther Creek High School",
    graduation: "May 2029",
    identity: ["Builder", "Strategist", "Musician", "Student", "Systems thinker"],
  },
  statement: "Different systems. One mindset: disciplined improvement.",
  chapters: [
    { number: "01", id: "intro", label: "Intro" },
    { number: "02", id: "build", label: "Build" },
    { number: "03", id: "trade", label: "Trade" },
    { number: "04", id: "perform", label: "Perform" },
    { number: "05", id: "lead", label: "Lead" },
    { number: "06", id: "future", label: "Future" },
  ],
  metrics: [
    { value: "120%", label: "portfolio return", detail: "five-month period · past performance" },
    { value: "3rd", label: "UIL State finish", detail: "marching band championships" },
    { value: "15–20", label: "hours / week", detail: "rehearsal and performance" },
    { value: "31053", label: "FTC team", detail: "FTX Combobulators" },
    { value: "360°", label: "movement", detail: "mecanum-wheel chassis" },
  ],
  projects: {
    robotics: {
      eyebrow: "Lead Engineer · FTC Robotics",
      title: "Motion, engineered.",
      summary: "A high-speed mecanum chassis and a precise projectile system, built through CAD-led iteration.",
      phases: [
        { label: "Problem", text: "Create fast, omnidirectional movement while keeping launch accuracy and total weight under control." },
        { label: "Approach", text: "Architect a mecanum-wheel chassis, model custom parts in CAD, and fabricate iterations with additive manufacturing." },
        { label: "Iteration", text: "Reduce mass, tighten the projectile mechanism, and contribute Java for autonomous and tele-op modes." },
        { label: "Result", text: "A lighter robot with 360-degree movement and a high-accuracy launching system for FTC Team 31053." },
      ],
      tags: ["CAD", "Java", "Mechanical design", "Additive manufacturing"],
    },
    trading: {
      eyebrow: "Independent Research · Quantitative Systems",
      title: "Signal. Validate. Control risk.",
      summary: "A proprietary Python scanner built to find price and volume structures across thousands of equities.",
      phases: [
        { label: "Signals", text: "Pennants, bull flags, VWAP, momentum shifts, and volume breakouts." },
        { label: "Scale", text: "Automated the scan of thousands of equities to surface a focused set of candidates." },
        { label: "Judgment", text: "Used a human-in-the-loop model to validate algorithmic signals before execution." },
        { label: "Risk", text: "Maintained dynamic position sizing, risk protocols, and automated stop-losses." },
      ],
      tags: ["Python", "Quantitative analysis", "Risk management", "Portfolio systems"],
    },
  },
  quantProjects: [
    { title: "Quant Backtesting Engine", summary: "Execution-aware backtesting with transaction costs, timing safeguards, and risk reporting.", technologies: ["Python", "pandas", "NumPy"], github: "https://github.com/aaraven99/quant-backtesting-engine" },
    { title: "Pairs Trading System", summary: "Cointegration screening, hedge-adjusted spread signals, and paper-only order workflows.", technologies: ["Python", "statsmodels", "Alpaca"], github: "https://github.com/aaraven99/pairs-trading-system" },
    { title: "Black-Scholes Options Lab", summary: "Pricing, Greeks, arbitrage checks, and implied-volatility estimation from first principles.", technologies: ["Python", "SciPy", "NumPy"], github: "https://github.com/aaraven99/black-scholes-options-lab" },
    { title: "Limit Order Book Simulator", summary: "A deterministic price-time-priority matching engine with partial fills and a trading API.", technologies: ["Python", "Flask", "WebSockets"], github: "https://github.com/aaraven99/limit-order-book-simulator" },
    { title: "Market Sentiment Correlation", summary: "Permitted-headline parsing and cautious forward-return sentiment research.", technologies: ["Python", "BeautifulSoup", "pandas"], github: "https://github.com/aaraven99/market-sentiment-correlation" },
    { title: "Portfolio Optimizer", summary: "Constrained mean-variance allocation for minimum risk, maximum Sharpe, and target returns.", technologies: ["Python", "SciPy", "Plotly"], github: "https://github.com/aaraven99/markowitz-portfolio-optimizer" },
    { title: "Monte Carlo Risk Lab", summary: "Seeded vectorized simulation for option prices, confidence intervals, VaR, and CVaR.", technologies: ["Python", "NumPy", "SciPy"], github: "https://github.com/aaraven99/monte-carlo-risk-lab" },
    { title: "Volatility Surface Visualizer", summary: "Option-chain cleaning, log-moneyness normalization, and interpolated volatility surfaces.", technologies: ["Python", "SciPy", "Plotly"], github: "https://github.com/aaraven99/volatility-surface-visualizer" },
    { title: "Fama-French Factor Model", summary: "Three-factor return attribution and alpha-significance testing.", technologies: ["Python", "statsmodels", "pandas"], github: "https://github.com/aaraven99/fama-french-factor-model" },
    { title: "Real-Time Market Dashboard", summary: "Responsive market interface with mock streaming, price statistics, and moving averages.", technologies: ["React", "TypeScript", "Recharts"], github: "https://github.com/aaraven99/realtime-market-dashboard" },
  ],
  skills: [
    { name: "Python", domain: "Code", level: 88 },
    { name: "Java", domain: "Code", level: 72 },
    { name: "CAD", domain: "Machines", level: 82 },
    { name: "Quantitative analysis", domain: "Capital", level: 84 },
    { name: "Mechanical design", domain: "Machines", level: 80 },
    { name: "Portfolio management", domain: "Capital", level: 77 },
    { name: "Music performance", domain: "Performance", level: 90 },
    { name: "Leadership", domain: "Community", level: 81 },
  ],
  timeline: [
    { year: "2025", title: "Entered Panther Creek", text: "Began a four-year high school chapter shaped by advanced coursework, performance, and engineering." },
    { year: "Freshman", title: "Qualified at state level", text: "Earned a place at the Texas State Solo & Ensemble Contest while developing consistency under pressure." },
    { year: "Now", title: "Building across systems", text: "Connecting code, markets, robotics, music, and community through deliberate practice." },
    { year: "2029", title: "Next launch point", text: "Expected graduation: May 2029." },
  ],
  awards: [
    { title: "3rd Place", detail: "UIL State Marching Band Championships", meta: "", description: "" },
    { title: "Top 25%", detail: "Geometry · Stanford Math Tournament", meta: "", description: "" },
    {
      title: "480",
      detail: "PLTW Introduction to Engineering Design EOC",
      meta: "Distinguished · May 2026 · Panther Creek High School",
      description: "Highest possible achievement tier on the national Project Lead The Way assessment, evaluating proficiency in 3D modeling, the engineering design process, and technical documentation.",
    },
  ],
  coursework: ["AP Precalculus", "AP Human Geography"],
  languages: ["Gujarati · limited working proficiency", "Spanish · elementary proficiency"],
  explorations: ["Robotics", "Quantitative systems", "Software", "Finance", "Creative technology"],
} as const;

export type ChapterId = (typeof portfolio.chapters)[number]["id"];
